Understand the Data

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("D:\\project\\proejcts 4\\Warehouse_and_Retail_Sales.csv")

In [5]:
data.head()

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0
2,2020,1,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0
3,2020,1,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0
4,2020,1,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0

In [6]:
data.shape

(307645, 9)

In [11]:
data.columns

Index(['YEAR', 'MONTH', 'SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION',
       'ITEM TYPE', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES'],
      dtype='str')

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307478 non-null  str
 3   ITEM CODE         307645 non-null  str
 4   ITEM DESCRIPTION  307645 non-null  str
 5   ITEM TYPE         307644 non-null  str
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 21.1 MB

In [13]:
data.isnull().sum()

YEAR                  0
MONTH                 0
SUPPLIER            167
ITEM CODE             0
ITEM DESCRIPTION      0
ITEM TYPE             1
RETAIL SALES          3
RETAIL TRANSFERS      0
WAREHOUSE SALES       0
dtype: int64

In [16]:
data.describe

<bound method NDFrame.describe of         YEAR  MONTH                             SUPPLIER ITEM CODE  \
0       2020      1    REPUBLIC NATIONAL DISTRIBUTING CO    100009
1       2020      1                            PWSWN INC    100024
2       2020      1              RELIABLE CHURCHILL LLLP      1001
3       2020      1            LANTERNA DISTRIBUTORS INC    100145
4       2020      1                 DIONYSOS IMPORTS INC    100293
...      ...    ...                                  ...       ...
307640  2020      9              BOSTON BEER CORPORATION     98868
307641  2020      9  GLOBAL OCEAN AND AIR CARGO SERVICES     98884
307642  2020      9                         HEINEKEN USA     98906
307643  2020      9              RELIABLE CHURCHILL LLLP     98914
307644  2020      9                CONSTANTINE WINES INC     98930

                           ITEM DESCRIPTION ITEM TYPE  RETAIL SALES  \
0                       BOOTLEG RED - 750ML      WINE          0.00
1                 MOMENT DE PLAISIR - 750ML      WINE          0.00
2       S SMITH ORGANIC PEAR CIDER - 18.7OZ      BEER          0.00
3             SCHLINK HAUS KABINETT - 750ML      WINE          0.00
4            SANTORINI GAVALA WHITE - 750ML      WINE          0.82
...                                     ...       ...           ...
307640           SAM ADAMS OCTOBERFEST 1/6K      KEGS          0.00
307641            HARAR BEER 4/6NR - 11.2OZ      BEER          1.50
307642                 DOS EQUIS LAGER 1/2K      KEGS          0.00
307643          LINDEMANS KRIEK NR - 25.4OZ      BEER          0.00
307644        ARIS GREEK LAGER 4/6NR - 11OZ      BEER          0.00

        RETAIL TRANSFERS  WAREHOUSE SALES
0                    0.0              2.0
1                    1.0              4.0
2                    0.0              1.0
3                    0.0              1.0
4                    0.0              0.0
...                  ...              ...
307640               0.0             54.0
307641               1.0              8.0
307642               0.0             22.0
307643               0.0              4.0
307644               0.0              0.0

[307645 rows x 9 columns]>

In [14]:
data.select_dtypes(include=['int64','float64']).columns

Index(['YEAR', 'MONTH', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES'], dtype='str')

In [15]:
data.select_dtypes(include=['object']).columns

C:\Users\hrush\AppData\Local\Temp\ipykernel_456\1092125542.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(include=['object']).columns

Index(['SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION', 'ITEM TYPE'], dtype='str')

In [17]:
data["SUPPLIER"].nunique()

396

In [18]:
data["ITEM TYPE"].value_counts()

ITEM TYPE
WINE            187640
LIQUOR           64910
BEER             42413
KEGS             10146
NON-ALCOHOL       1908
STR_SUPPLIES       405
REF                127
DUNNAGE             95
Name: count, dtype: int64

In [19]:
data.duplicated().sum()

np.int64(0)

In [22]:
data.duplicated().sum()

np.int64(0)

In [23]:
data.describe()

,YEAR,MONTH,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
count,307645.000000,307645.000000,307642.000000,307645.000000,307645.000000
mean,2018.438525,6.423862,7.024071,6.936465,25.294597
std,1.083061,3.461812,30.986238,30.237195,249.916798
min,2017.000000,1.000000,-6.490000,-38.490000,-7800.000000
25%,2017.000000,3.000000,0.000000,0.000000,0.000000
50%,2019.000000,7.000000,0.320000,0.000000,1.000000
75%,2019.000000,9.000000,3.267500,3.000000,5.000000
max,2020.000000,12.000000,2739.000000,1990.830000,18317.000000

In [30]:

data['ITEM TYPE'].value_counts().head(20)

ITEM TYPE
WINE            187640
LIQUOR           64910
BEER             42413
KEGS             10146
NON-ALCOHOL       1908
STR_SUPPLIES       405
REF                127
DUNNAGE             95
Name: count, dtype: int64

In [25]:
data['MONTH'].unique()

array([ 1,  7,  3,  9,  6,  8, 12, 10, 11,  2,  4,  5])

In [26]:
data['YEAR'].unique()

array([2020, 2017, 2018, 2019])

In [27]:
(data['RETAIL SALES'] < 0).sum()

np.int64(113)

In [28]:
(data['RETAIL TRANSFERS'] < 0).sum()

np.int64(1016)

In [29]:
(data['WAREHOUSE SALES'] < 0).sum()

np.int64(716)

In [31]:
data[data['ITEM TYPE'].isnull()]

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
106780,2017,10,REPUBLIC NATIONAL DISTRIBUTING CO,347939,FONTANAFREDDA BAROLO SILVER LABEL 750 ML,NaN,0.0,0.0,1.0

In [32]:
data['ITEM TYPE'] = data['ITEM TYPE'].fillna('Unknown')

In [33]:
data[data['ITEM TYPE'].isnull()]

Empty DataFrame
Columns: [YEAR, MONTH, SUPPLIER, ITEM CODE, ITEM DESCRIPTION, ITEM TYPE, RETAIL SALES, RETAIL TRANSFERS, WAREHOUSE SALES]
Index: []

In [34]:
data = data.dropna(subset=['RETAIL SALES'])

In [35]:
data[data['RETAIL SALES'] < 0]

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
4694,2020,1,CONSTANTINE WINES INC,336527,UNDERWOOD ROSE - 750ML,WINE,-0.34,0.0,2.0
6487,2020,1,"THE COUNTRY VINTNER, LLC DBA WINEBOW",384534,CH MUSAR JEUNE RGE - 750ML,WINE,-0.17,0.0,1.0
8434,2020,1,Default,59781,STORE SPECIAL WINE 750 ML - 750ML,REF,-0.08,0.0,0.0
9843,2020,1,DIAGEO NORTH AMERICA INC,72045,DALWHINNIE WINTER FROST(STARK) - 750ML,LIQUOR,-0.17,0.0,0.0
16185,2020,7,STEFANO INCORPORATED,332333,INTIPALKA CHARD 13 - 750ML,WINE,-0.42,0.0,0.0
...,...,...,...,...,...,...,...,...,...
289859,2019,10,WAGNER WINE COMPANY LLC,48777,MER SOLEIL SANTA LUCIA HIGHLANDS CHARD - 750ML,WINE,-0.17,0.0,0.0
290279,2019,10,BACARDI USA INC,53520,DEWARS SIGNATURE SCOTCH - 750ML,LIQUOR,-0.25,0.0,0.0
291653,2019,10,AMERICAN BEVERAGE MARKETERS,70727,MASTER OF MIXES MOJITO - 1L,NON-ALCOHOL,-0.08,0.0,0.0
300200,2019,11,OPICI FAMILY DISTRIBUTING OF MD,346400,DRUNKEN SAILOR SPICED RUM - 750ML,LIQUOR,-1.17,0.0,0.0
302991,2019,11,PWSWN INC,48512,BULGARIANA CAB/SYR 329148 - 750ML,WINE,-0.17,1.0,0.0

In [36]:
data[data['RETAIL TRANSFERS'] < 0]

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
2215,2020,1,NORTH LOCK LLC DBA PORT CITY BREWING CO,25738,PORT CITY MONUMENTAL IPA 4/6 12 OZ,BEER,3.25,-1.0,17.0
6659,2020,1,JACK POUST & COMPANY INC,40088,PRESIDENTIAL LBV PORT 6/CS - 750ML,WINE,1.19,-2.0,0.0
9644,2020,1,STEFANO INCORPORATED,70941,EFE RAKI GREEN LABEL - 750ML,LIQUOR,0.72,-2.0,0.0
11153,2020,1,BROWN-FORMAN BEVERAGES WORLDWIDE,84089,KORBEL ORGANIC BRUT CHAMPAGNE - 750ML,WINE,0.67,-3.2,0.0
11696,2020,1,SAZERAC CO,92140,FIREBALL CINNAMON WHISKY PET - 1.75L,LIQUOR,2.20,-1.0,0.0
...,...,...,...,...,...,...,...,...,...
294300,2019,10,BUCK DISTRIBUTING COMPANY INC,98302,CARIB SHANDY GINGER 4/6 NR - 12OZ,BEER,2.70,-10.0,4.0
301644,2019,11,RELIABLE CHURCHILL LLLP,39705,LITTLE PENGUIN SHZ - 1.5L,WINE,2.68,-1.0,0.0
303241,2019,11,DEUTSCH FAMILY WINE & SPIRITS,50903,VILLA MASSA LIMONI - 750ML,LIQUOR,8.10,-1.0,0.0
303753,2019,11,BACARDI USA INC,62227,GREY GOOSE VODKA - 50ML,LIQUOR,2.14,-20.0,0.0
307278,2019,11,DOGFISH HEAD CRAFT BREWERY LLC,99023,DOGFISH HEAD PUNKIN ALE 4/6 NR - 12OZ,BEER,4.62,-3.0,3.0

In [37]:
data[data['WAREHOUSE SALES'] < 0]

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
405,2020,1,NaN,1279,EMPTY WINE KEG - KEGS,DUNNAGE,0.0,0.0,-12.0
822,2020,1,PREMIUM DISTRIBUTORS INC,175,EMPTY 1/2 KEG (30.00),DUNNAGE,0.0,0.0,-3999.0
1011,2020,1,ANHEUSER BUSCH INC,205,EMPTY 1/6 KEG (30.00),DUNNAGE,0.0,0.0,-934.0
1552,2020,1,FIVE GRAPES LLC,236502,J DE TELMONT SANS SOUFRE AJOUTE BRUT CHAMP - 7...,WINE,0.0,0.0,-1.0
2144,2020,1,LEGENDS LTD,25049,ERDINGER HEFE WEISSE 50L 1/2K,KEGS,0.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...
307287,2019,11,LABATT USA OPERATING CO LLC,99333,MAGIC HAT #9 1/2 KEG,KEGS,0.0,0.0,-2.0
307312,2019,11,NaN,BC,BEER CREDIT,REF,0.0,0.0,-123.0
307313,2019,11,NaN,WC,WINE CREDIT,REF,0.0,0.0,-275.0
307462,2020,9,PUNTO VINO LLC,427677,PAUL DIREDER ZWEIGELT - 1L,WINE,0.0,0.0,-1.0
307604,2020,9,NaN,WC,WINE CREDIT,REF,0.0,0.0,-70.0

In [38]:
data[data['RETAIL SALES'] == data['RETAIL SALES'].max()]

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
12941,2020,7,NaN,2,ICE,NON-ALCOHOL,2739.0,0.0,0.0

In [39]:
data.nlargest(10, 'RETAIL SALES')

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
12941,2020,7,NaN,2,ICE,NON-ALCOHOL,2739.00,0.00,0.00
31986,2020,3,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1816.49,1990.83,10.00
265163,2019,8,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1752.45,1448.00,31.00
240325,2019,6,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1710.80,1470.17,22.00
138362,2017,12,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1616.60,1587.99,15.00
292809,2019,10,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1615.23,1462.00,23.00
233222,2019,6,CROWN IMPORTS,23445,CORONA EXTRA LOOSE NR - 12OZ,BEER,1494.00,1462.00,14739.92
19778,2020,7,FIFTH GENERATION INC,53929,TITO'S HANDMADE VODKA - 1.75L,LIQUOR,1482.17,1507.00,22.00
307323,2020,9,NaN,2,ICE,NON-ALCOHOL,1445.00,0.00,0.00
258025,2019,8,CROWN IMPORTS,23445,CORONA EXTRA LOOSE NR - 12OZ,BEER,1417.00,1437.00,9097.92

In [40]:
clean_data = data.copy()

In [41]:
clean_data.isnull().sum()

YEAR                  0
MONTH                 0
SUPPLIER            164
ITEM CODE             0
ITEM DESCRIPTION      0
ITEM TYPE             0
RETAIL SALES          0
RETAIL TRANSFERS      0
WAREHOUSE SALES       0
dtype: int64

In [42]:
clean_data[clean_data['SUPPLIER'].isnull()].head()

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
106,2020,1,NaN,107,JIGGER MEASURE SHOT GLASS,STR_SUPPLIES,14.69,18.0,0.0
188,2020,1,NaN,113,BARTENDERS BLACK BOOK,STR_SUPPLIES,0.40,0.0,0.0
231,2020,1,NaN,115,PLASTIC SHOT GLASS PACK,STR_SUPPLIES,5.71,6.0,0.0
252,2020,1,NaN,117,WHISKEY TASTING JOURNAL,STR_SUPPLIES,0.08,0.0,0.0
261,2020,1,NaN,118,PLASTIC WINE GLASS PACK,STR_SUPPLIES,7.40,10.0,0.0

In [43]:
clean_data['SUPPLIER'] = clean_data['SUPPLIER'].fillna('Unknown Supplier')

In [44]:
clean_data.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [45]:
clean_data[clean_data['ITEM TYPE'].isnull()]

Empty DataFrame
Columns: [YEAR, MONTH, SUPPLIER, ITEM CODE, ITEM DESCRIPTION, ITEM TYPE, RETAIL SALES, RETAIL TRANSFERS, WAREHOUSE SALES]
Index: []

In [46]:
clean_data[clean_data['RETAIL SALES'].isnull()]

Empty DataFrame
Columns: [YEAR, MONTH, SUPPLIER, ITEM CODE, ITEM DESCRIPTION, ITEM TYPE, RETAIL SALES, RETAIL TRANSFERS, WAREHOUSE SALES]
Index: []

In [47]:
clean_data.duplicated().sum()

np.int64(0)

In [48]:
clean_data['DATE'] = pd.to_datetime(
    clean_data['YEAR'].astype(str) + '-' +
    clean_data['MONTH'].astype(str) + '-01'
)

In [49]:
clean_data[['YEAR','MONTH','DATE']].head()

   YEAR  MONTH       DATE
0  2020      1 2020-01-01
1  2020      1 2020-01-01
2  2020      1 2020-01-01
3  2020      1 2020-01-01
4  2020      1 2020-01-01

In [50]:
clean_data.info()

<class 'pandas.DataFrame'>
Index: 307642 entries, 0 to 307644
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307642 non-null  int64
 1   MONTH             307642 non-null  int64
 2   SUPPLIER          307642 non-null  str
 3   ITEM CODE         307642 non-null  str
 4   ITEM DESCRIPTION  307642 non-null  str
 5   ITEM TYPE         307642 non-null  str
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307642 non-null  float64
 8   WAREHOUSE SALES   307642 non-null  float64
 9   DATE              307642 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(4)
memory usage: 25.8 MB

In [51]:
clean_data.to_csv(
    "cleaned_sales_data.csv",
    index=False
)

In [52]:
clean_data.shape

(307642, 10)

In [53]:
clean_data.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
DATE                0
dtype: int64

In [54]:
clean_data.duplicated().sum()

np.int64(0)

In [55]:
clean_data.describe()

,YEAR,MONTH,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,DATE
count,307642.000000,307642.000000,307642.000000,307642.000000,307642.000000,307642
mean,2018.438510,6.423843,7.024071,6.936532,25.294844,2018-11-21 10:17:37.618920
min,2017.000000,1.000000,-6.490000,-38.490000,-7800.000000,2017-06-01 00:00:00
25%,2017.000000,3.000000,0.000000,0.000000,0.000000,2017-11-01 00:00:00
50%,2019.000000,7.000000,0.320000,0.000000,1.000000,2019-03-01 00:00:00
75%,2019.000000,9.000000,3.267500,3.000000,5.000000,2019-09-01 00:00:00
max,2020.000000,12.000000,2739.000000,1990.830000,18317.000000,2020-09-01 00:00:00
std,1.083055,3.461823,30.986238,30.237335,249.918004,NaN

Question 1: Overall Business Performance

In [56]:
clean_data['RETAIL SALES'].sum()

np.float64(2160899.37)

In [57]:
clean_data['RETAIL TRANSFERS'].sum()

np.float64(2133968.63)

In [58]:
clean_data['WAREHOUSE SALES'].sum()

np.float64(7781756.28)

Question 2: Sales by Year

In [59]:
yearly_sales = clean_data.groupby('YEAR')['RETAIL SALES'].sum()

yearly_sales

YEAR
2017    686734.57
2018    153595.90
2019    960191.20
2020    360377.70
Name: RETAIL SALES, dtype: float64

Question 3: Sales by Product Category

In [60]:
category_sales = clean_data.groupby('ITEM TYPE')['RETAIL SALES'].sum().sort_values(ascending=False)

category_sales

ITEM TYPE
LIQUOR          802691.43
WINE            746498.59
BEER            574220.53
NON-ALCOHOL      34084.31
STR_SUPPLIES      2740.88
REF                663.63
KEGS                 0.00
DUNNAGE              0.00
Unknown              0.00
Name: RETAIL SALES, dtype: float64

Question 4: Top Suppliers

In [61]:
supplier_sales = clean_data.groupby('SUPPLIER')['RETAIL SALES'].sum().sort_values(ascending=False)

supplier_sales.head(10)

SUPPLIER
E & J GALLO WINERY          166170.53
DIAGEO NORTH AMERICA INC    145343.20
CONSTELLATION BRANDS        131664.79
ANHEUSER BUSCH INC          109960.82
JIM BEAM BRANDS CO           96164.04
MILLER BREWING COMPANY       87156.44
CROWN IMPORTS                84437.66
SAZERAC CO                   70414.62
BACARDI USA INC              66610.23
THE WINE GROUP               64270.04
Name: RETAIL SALES, dtype: float64

Question 5: Monthly Sales Trend

In [62]:
monthly_sales = clean_data.groupby('DATE')['RETAIL SALES'].sum()

monthly_sales

DATE
2017-06-01     97357.26
2017-07-01     92625.29
2017-08-01     87111.78
2017-09-01     90452.60
2017-10-01     89236.96
2017-11-01     98316.19
2017-12-01    131634.49
2018-01-01     75791.77
2018-02-01     77804.13
2019-01-01     76100.53
2019-02-01     80113.54
2019-03-01     84441.04
2019-04-01     80342.58
2019-05-01     94953.10
2019-06-01     90860.39
2019-07-01     90763.48
2019-08-01     90628.61
2019-09-01     82126.21
2019-10-01     88230.41
2019-11-01    101631.31
2020-01-01     74318.77
2020-03-01    109411.29
2020-07-01     94538.96
2020-09-01     82108.68
Name: RETAIL SALES, dtype: float64

In [63]:
clean_data['RETAIL SALES'].sum()

np.float64(2160899.37)

In [64]:
clean_data.groupby('YEAR')['RETAIL SALES'].sum()

YEAR
2017    686734.57
2018    153595.90
2019    960191.20
2020    360377.70
Name: RETAIL SALES, dtype: float64

In [65]:
clean_data.groupby('ITEM TYPE')['RETAIL SALES'].sum().sort_values(ascending=False)

ITEM TYPE
LIQUOR          802691.43
WINE            746498.59
BEER            574220.53
NON-ALCOHOL      34084.31
STR_SUPPLIES      2740.88
REF                663.63
KEGS                 0.00
DUNNAGE              0.00
Unknown              0.00
Name: RETAIL SALES, dtype: float64

In [66]:
clean_data.groupby('SUPPLIER')['RETAIL SALES'].sum().head(10)

SUPPLIER
8 VINI INC                     2.53
A HARDY USA LTD                0.56
A I G WINE & SPIRITS          13.24
A VINTNERS SELECTIONS       9482.87
A&E INC                       11.49
A&W BORDERS LLC                1.30
ADAMBA IMPORTS INTL           78.86
AIKO IMPORTERS INC            14.73
ALLAGASH BREWING COMPANY     751.34
ALLIED IMPORTERS USA LTD      12.52
Name: RETAIL SALES, dtype: float64

In [67]:
clean_data.groupby('DATE')['RETAIL SALES'].sum()

DATE
2017-06-01     97357.26
2017-07-01     92625.29
2017-08-01     87111.78
2017-09-01     90452.60
2017-10-01     89236.96
2017-11-01     98316.19
2017-12-01    131634.49
2018-01-01     75791.77
2018-02-01     77804.13
2019-01-01     76100.53
2019-02-01     80113.54
2019-03-01     84441.04
2019-04-01     80342.58
2019-05-01     94953.10
2019-06-01     90860.39
2019-07-01     90763.48
2019-08-01     90628.61
2019-09-01     82126.21
2019-10-01     88230.41
2019-11-01    101631.31
2020-01-01     74318.77
2020-03-01    109411.29
2020-07-01     94538.96
2020-09-01     82108.68
Name: RETAIL SALES, dtype: float64

In [68]:
yearly_sales = clean_data.groupby('YEAR')['RETAIL SALES'].sum()

yearly_growth = yearly_sales.pct_change() * 100

yearly_growth

YEAR
2017           NaN
2018    -77.633877
2019    525.141166
2020    -62.468131
Name: RETAIL SALES, dtype: float64

In [69]:
clean_data['YEAR'].value_counts().sort_index()

YEAR
2017     96284
2018     26445
2019    138638
2020     46275
Name: count, dtype: int64

In [70]:
clean_data.groupby('YEAR')['MONTH'].unique()

YEAR
2017               [6, 7, 8, 12, 9, 10, 11]
2018                                 [1, 2]
2019    [1, 11, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2020                           [1, 7, 3, 9]
Name: MONTH, dtype: object

In [71]:
clean_data.groupby('YEAR')['MONTH'].nunique()

YEAR
2017     7
2018     2
2019    11
2020     4
Name: MONTH, dtype: int64

In [72]:
clean_data['YEAR'].value_counts().sort_index()

YEAR
2017     96284
2018     26445
2019    138638
2020     46275
Name: count, dtype: int64

In [73]:
clean_data.groupby('YEAR')['MONTH'].nunique()

YEAR
2017     7
2018     2
2019    11
2020     4
Name: MONTH, dtype: int64

In [75]:
monthly_year_sales = (
    clean_data
    .groupby(['YEAR','MONTH'])['RETAIL SALES']
    .sum()
)

monthly_year_sales

YEAR  MONTH
2017  6         97357.26
      7         92625.29
      8         87111.78
      9         90452.60
      10        89236.96
      11        98316.19
      12       131634.49
2018  1         75791.77
      2         77804.13
2019  1         76100.53
      2         80113.54
      3         84441.04
      4         80342.58
      5         94953.10
      6         90860.39
      7         90763.48
      8         90628.61
      9         82126.21
      10        88230.41
      11       101631.31
2020  1         74318.77
      3        109411.29
      7         94538.96
      9         82108.68
Name: RETAIL SALES, dtype: float64

In [76]:
avg_monthly_sales = (
    monthly_year_sales
    .groupby('YEAR')
    .mean()
)

avg_monthly_sales

YEAR
2017    98104.938571
2018    76797.950000
2019    87290.109091
2020    90094.425000
Name: RETAIL SALES, dtype: float64

In [77]:
category_sales = (
    clean_data
    .groupby('ITEM TYPE')['RETAIL SALES']
    .sum()
    .sort_values(ascending=False)
)

category_percentage = (
    category_sales / category_sales.sum() * 100
)

category_percentage

ITEM TYPE
LIQUOR          37.146174
WINE            34.545736
BEER            26.573219
NON-ALCOHOL      1.577321
STR_SUPPLIES     0.126840
REF              0.030711
KEGS             0.000000
DUNNAGE          0.000000
Unknown          0.000000
Name: RETAIL SALES, dtype: float64

In [78]:
monthly_year_sales = (
    clean_data
    .groupby(['YEAR','MONTH'])['RETAIL SALES']
    .sum()
)

avg_monthly_sales = (
    monthly_year_sales
    .groupby('YEAR')
    .mean()
)

avg_monthly_sales

YEAR
2017    98104.938571
2018    76797.950000
2019    87290.109091
2020    90094.425000
Name: RETAIL SALES, dtype: float64

In [79]:
category_percentage

ITEM TYPE
LIQUOR          37.146174
WINE            34.545736
BEER            26.573219
NON-ALCOHOL      1.577321
STR_SUPPLIES     0.126840
REF              0.030711
KEGS             0.000000
DUNNAGE          0.000000
Unknown          0.000000
Name: RETAIL SALES, dtype: float64

Question: Which suppliers drive the most sales?

In [80]:
top_suppliers = (
    clean_data
    .groupby('SUPPLIER')['RETAIL SALES']
    .sum()
    .sort_values(ascending=False)
)

top_suppliers.head(10)

SUPPLIER
E & J GALLO WINERY          166170.53
DIAGEO NORTH AMERICA INC    145343.20
CONSTELLATION BRANDS        131664.79
ANHEUSER BUSCH INC          109960.82
JIM BEAM BRANDS CO           96164.04
MILLER BREWING COMPANY       87156.44
CROWN IMPORTS                84437.66
SAZERAC CO                   70414.62
BACARDI USA INC              66610.23
THE WINE GROUP               64270.04
Name: RETAIL SALES, dtype: float64

Question: Which products drive sales?

In [81]:
top_products = (
    clean_data
    .groupby('ITEM DESCRIPTION')['RETAIL SALES']
    .sum()
    .sort_values(ascending=False)
)

top_products.head(10)

ITEM DESCRIPTION
TITO'S HANDMADE VODKA - 1.75L                27580.50
CORONA EXTRA LOOSE NR - 12OZ                 25064.00
HEINEKEN LOOSE NR - 12OZ                     17761.00
MILLER LITE 30PK CAN - 12OZ                  14440.00
BUD LIGHT 30PK CAN                           12299.00
BOWMAN'S VODKA - 1.75L                       12126.72
MILLER LITE  HIGH GRAPHIC LOOSE NR - 12OZ    10373.77
STELLA ARTOIS LOOSE NR - 11.2OZ              10354.00
CORONA EXTRA 2/12 NR - 12OZ                   9755.19
PINNACLE VODKA - 1.75L                        8676.40
Name: RETAIL SALES, dtype: float64

Question: Are there seasonal patterns?

In [82]:
monthly_sales = (
    clean_data
    .groupby('MONTH')['RETAIL SALES']
    .sum()
)

monthly_sales

MONTH
1     226211.07
2     157917.67
3     193852.33
4      80342.58
5      94953.10
6     188217.65
7     277927.73
8     177740.39
9     254687.49
10    177467.37
11    199947.50
12    131634.49
Name: RETAIL SALES, dtype: float64

In [83]:
total_sales = clean_data['RETAIL SALES'].sum()
total_sales

np.float64(2160899.37)

In [84]:
total_sales = clean_data['RETAIL SALES'].sum()
total_sales

np.float64(2160899.37)

In [85]:
total_sales = clean_data['RETAIL SALES'].sum()
total_sales

np.float64(2160899.37)

In [86]:
clean_data['ITEM DESCRIPTION'].nunique()

34820

In [87]:
clean_data['SUPPLIER'].nunique()

397

In [88]:
clean_data.to_csv(
    "cleaned_retail_sales_analysis.csv",
    index=False
)

In [89]:
clean_data['WAREHOUSE SALES'].sum()

np.float64(7781756.28)

In [90]:
clean_data['RETAIL TRANSFERS'].sum()

np.float64(2133968.63)

In [91]:
clean_data['ITEM DESCRIPTION'].nunique()

34820

In [92]:
clean_data['SUPPLIER'].nunique()

397

In [93]:
clean_data['WAREHOUSE SALES'].sum() / clean_data['RETAIL SALES'].sum()

np.float64(3.6011655091555697)

In [94]:
clean_data.to_csv(
    "cleaned_retail_sales_analysis.csv",
    index=False
)